# Generated by Django 4.1.1 on 2022-09-06 13:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('main_image', models.ImageField(upload_to='main/', verbose_name='main image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('contact', models.CharField(max_length=100, verbose_name='contact')),
                ('about', models.CharField(max_length=100, verbose_name='about')),
                ('banner_image', models.ImageField(upload_to='banner', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homies',
            },
        ),
    ]
