# Generated by Django 4.1.1 on 2022-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='banner_image',
            field=models.ImageField(upload_to='banner/', verbose_name='banner image'),
        ),
    ]
