# Generated by Django 4.1.1 on 2022-09-08 10:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_workmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='about_en',
            field=models.CharField(max_length=100, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='about_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='about_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='contact_en',
            field=models.CharField(max_length=100, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='contact_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='contact_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='full_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
